name: push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "README.md"

jobs:
  push:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jre_ver:
          [
            8-jre-base,
            11-jre-headless,
            17-jre-headless,
            21-jre-headless,
          ]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-id
        run: |
          id=$(echo ${{ matrix.jre_ver }} | cut -d- -f1)
          echo "::set-output name=id::$id"
      - run: echo "${{steps.get-id.outputs.id}}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.15.0
        with:
          build-args: |
            JRE_VERSION=${{ matrix.jre_ver }}
          push: true
          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: vsaps/java:${{ steps.get-id.outputs.id }}
  update-readme:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - uses: actions/checkout@v4
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: redblackcs/java
          short-description: ${{ github.event.repository.description }}
